# CMake generated Testfile for 
# Source directory: /home/jan/projects/linux-colonize
# Build directory: /home/jan/projects/linux-colonize/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[unit_col1_save]=] "/home/jan/projects/linux-colonize/build-release/unit_col1_save")
set_tests_properties([=[unit_col1_save]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;190;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_settings]=] "/home/jan/projects/linux-colonize/build-release/unit_settings")
set_tests_properties([=[unit_settings]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;202;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_new_game]=] "/home/jan/projects/linux-colonize/build-release/unit_new_game")
set_tests_properties([=[unit_new_game]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;355;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_hall_of_fame]=] "/home/jan/projects/linux-colonize/build-release/unit_hall_of_fame")
set_tests_properties([=[unit_hall_of_fame]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;437;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_popup]=] "/home/jan/projects/linux-colonize/build-release/smoke_popup")
set_tests_properties([=[smoke_popup]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;455;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_ai_popup]=] "/home/jan/projects/linux-colonize/build-release/smoke_ai_popup")
set_tests_properties([=[smoke_ai_popup]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;467;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_popup_dialogs]=] "/home/jan/projects/linux-colonize/build-release/smoke_popup_dialogs")
set_tests_properties([=[smoke_popup_dialogs]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;476;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_pick_music]=] "/home/jan/projects/linux-colonize/build-release/smoke_pick_music")
set_tests_properties([=[smoke_pick_music]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;503;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_save_load_dialog]=] "/home/jan/projects/linux-colonize/build-release/smoke_save_load_dialog")
set_tests_properties([=[smoke_save_load_dialog]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;514;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_map]=] "/home/jan/projects/linux-colonize/build-release/unit_map")
set_tests_properties([=[unit_map]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;528;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_map_gen]=] "/home/jan/projects/linux-colonize/build-release/unit_map_gen")
set_tests_properties([=[unit_map_gen]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;540;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_mapgen_seed100]=] "/home/jan/projects/linux-colonize/build-release/golden_mapgen_seed100")
set_tests_properties([=[golden_mapgen_seed100]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;552;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_viceroy_tables]=] "/home/jan/projects/linux-colonize/build-release/smoke_viceroy_tables")
set_tests_properties([=[smoke_viceroy_tables]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;625;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_pedia]=] "/home/jan/projects/linux-colonize/build-release/unit_pedia")
set_tests_properties([=[unit_pedia]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;638;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_europe]=] "/home/jan/projects/linux-colonize/build-release/unit_europe")
set_tests_properties([=[unit_europe]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;651;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_colony_screen]=] "/home/jan/projects/linux-colonize/build-release/unit_colony_screen")
set_tests_properties([=[unit_colony_screen]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;664;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_map_panel]=] "/home/jan/projects/linux-colonize/build-release/unit_map_panel")
set_tests_properties([=[unit_map_panel]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;676;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_units]=] "/home/jan/projects/linux-colonize/build-release/unit_units")
set_tests_properties([=[unit_units]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;713;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_colony_yield]=] "/home/jan/projects/linux-colonize/build-release/unit_colony_yield")
set_tests_properties([=[unit_colony_yield]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;726;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_colonies]=] "/home/jan/projects/linux-colonize/build-release/unit_colonies")
set_tests_properties([=[unit_colonies]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;764;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_reports]=] "/home/jan/projects/linux-colonize/build-release/unit_reports")
set_tests_properties([=[unit_reports]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;803;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_text_edit]=] "/home/jan/projects/linux-colonize/build-release/unit_text_edit")
set_tests_properties([=[unit_text_edit]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;815;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_map_menu]=] "/home/jan/projects/linux-colonize/build-release/unit_map_menu")
set_tests_properties([=[unit_map_menu]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;827;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_turn]=] "/home/jan/projects/linux-colonize/build-release/unit_turn")
set_tests_properties([=[unit_turn]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;839;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ff]=] "/home/jan/projects/linux-colonize/build-release/unit_ff")
set_tests_properties([=[unit_ff]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;854;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_woodcut]=] "/home/jan/projects/linux-colonize/build-release/unit_woodcut")
set_tests_properties([=[unit_woodcut]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;873;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_declaration]=] "/home/jan/projects/linux-colonize/build-release/unit_declaration")
set_tests_properties([=[unit_declaration]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;891;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_closing]=] "/home/jan/projects/linux-colonize/build-release/unit_closing")
set_tests_properties([=[unit_closing]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;909;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_opening]=] "/home/jan/projects/linux-colonize/build-release/unit_opening")
set_tests_properties([=[unit_opening]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;927;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_ss]=] "/home/jan/projects/linux-colonize/build-release/smoke_ss")
set_tests_properties([=[smoke_ss]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;943;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_assets]=] "/home/jan/projects/linux-colonize/build-release/smoke_assets")
set_tests_properties([=[smoke_assets]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;957;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_popup_msg]=] "/home/jan/projects/linux-colonize/build-release/unit_popup_msg")
set_tests_properties([=[unit_popup_msg]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;972;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_pik]=] "/home/jan/projects/linux-colonize/build-release/smoke_pik")
set_tests_properties([=[smoke_pik]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;988;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai]=] "/home/jan/projects/linux-colonize/build-release/unit_ai")
set_tests_properties([=[unit_ai]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1000;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_goals]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_goals")
set_tests_properties([=[unit_ai_goals]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1012;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_contact]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_contact")
set_tests_properties([=[unit_ai_contact]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1024;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_diplo]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_diplo")
set_tests_properties([=[unit_ai_diplo]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1036;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_king]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_king")
set_tests_properties([=[unit_ai_king]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1048;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_euro_expand]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_euro_expand")
set_tests_properties([=[unit_ai_euro_expand]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1066;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_euro_war]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_euro_war")
set_tests_properties([=[unit_ai_euro_war]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1078;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_euro_20e6]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_euro_20e6")
set_tests_properties([=[unit_ai_euro_20e6]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1090;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_ai_euro_28c8_job_score]=] "/home/jan/projects/linux-colonize/build-release/unit_ai_euro_28c8_job_score")
set_tests_properties([=[unit_ai_euro_28c8_job_score]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1102;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_founding_fathers]=] "/home/jan/projects/linux-colonize/build-release/unit_founding_fathers")
set_tests_properties([=[unit_founding_fathers]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1114;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[unit_kill_indians]=] "/home/jan/projects/linux-colonize/build-release/unit_kill_indians")
set_tests_properties([=[unit_kill_indians]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1126;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_ai_turns]=] "/home/jan/projects/linux-colonize/build-release/golden_ai_turns")
set_tests_properties([=[golden_ai_turns]=] PROPERTIES  DISABLED "TRUE" WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1138;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_ai_mid01]=] "/home/jan/projects/linux-colonize/build-release/golden_ai_mid01")
set_tests_properties([=[golden_ai_mid01]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1148;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_ai_late01]=] "/home/jan/projects/linux-colonize/build-release/golden_ai_late01")
set_tests_properties([=[golden_ai_late01]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1157;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_colony_prod01]=] "/home/jan/projects/linux-colonize/build-release/golden_colony_prod01")
set_tests_properties([=[golden_colony_prod01]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1193;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_colony_preview01]=] "/home/jan/projects/linux-colonize/build-release/golden_colony_preview01")
set_tests_properties([=[golden_colony_preview01]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1203;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_market_prices01]=] "/home/jan/projects/linux-colonize/build-release/golden_market_prices01")
set_tests_properties([=[golden_market_prices01]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1213;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_woi_ref01]=] "/home/jan/projects/linux-colonize/build-release/golden_woi_ref01")
set_tests_properties([=[golden_woi_ref01]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1223;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_colony_prod02]=] "/home/jan/projects/linux-colonize/build-release/golden_colony_prod02")
set_tests_properties([=[golden_colony_prod02]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1233;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_colony_prod03]=] "/home/jan/projects/linux-colonize/build-release/golden_colony_prod03")
set_tests_properties([=[golden_colony_prod03]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1243;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[golden_ai_joint]=] "/usr/bin/cmake" "--build" "/home/jan/projects/linux-colonize/build-release" "--target" "golden_ai_joint")
set_tests_properties([=[golden_ai_joint]=] PROPERTIES  DISABLED "TRUE" WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1258;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_sound]=] "/home/jan/projects/linux-colonize/build-release/smoke_sound")
set_tests_properties([=[smoke_sound]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1286;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_game_flow]=] "/home/jan/projects/linux-colonize/build-release/smoke_game_flow")
set_tests_properties([=[smoke_game_flow]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1319;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
add_test([=[smoke_play]=] "/home/jan/projects/linux-colonize/build-release/smoke_play")
set_tests_properties([=[smoke_play]=] PROPERTIES  WORKING_DIRECTORY "/home/jan/projects/linux-colonize" _BACKTRACE_TRIPLES "/home/jan/projects/linux-colonize/CMakeLists.txt;1401;add_test;/home/jan/projects/linux-colonize/CMakeLists.txt;0;")
