[sdl]
fullscreen=false
vsync=false
output=texture
autolock=false

[cpu]
core=normal
cycles=max

[dosbox]
title=VR_BRAVE dump
memsize=16

[render]
scaler=none

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=none

[speaker]
pcspeaker=false

[autoexec]
@echo off
mount c .
c:
VR_BRAVE.EXE
