#!/usr/bin/env python3
"""Extract static data tables from COLONIZE/VICEROY.EXE into src/data/viceroy_tables.c."""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXE = ROOT / "COLONIZE" / "VICEROY.EXE"
OUT_C = ROOT / "src" / "data" / "viceroy_tables.c"

# Anchor: river transition table at DS:0x54de (verified against viceroy.c usage).
DS_RIVER_TRANSITION = 0x54DE
RIVER_TRANSITION = bytes(
    [7, 4, 2, 1, 1, 0, 0, 7, 11, 13, 14, 0, 23, 44, 53, 73, 75, 0, 27, 22, 37, 18, 48, 0, 3, 20, 25, 5]
)

TABLES = {
    "terrain_meta": {"ds": 0x543F, "count": 29, "elem": 0x34},
    "tile_display": {"ds": 0x5234, "count": 29, "elem": 0x0E},
    "river_transition": {"ds": DS_RIVER_TRANSITION, "count": 28, "elem": 1},
    "feature_sprite_bases_a": {"ds": 0x54FC, "count": 4, "elem": 1},
    "feature_sprite_bases_b": {"ds": 0x5502, "count": 4, "elem": 1},
    "connectivity_transition": {"ds": 0x5599, "count": 21, "elem": 1},
}


def ds_to_file(ds_offset: int, ds_to_file: int) -> int:
    return ds_offset + ds_to_file


def format_array(name: str, values: list[int], elems_per_row: int) -> str:
    lines = [f"const uint8_t {name}[] = {{"]
    for i in range(0, len(values), elems_per_row):
        chunk = values[i : i + elems_per_row]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def format_matrix(name: str, rows: list[list[int]]) -> str:
    elem = len(rows[0])
    lines = [f"const uint8_t {name}[{len(rows)}][{elem}] = {{"]
    for row in rows:
        lines.append("  {" + ", ".join(f"0x{b:02x}" for b in row) + "},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if not EXE.is_file():
        print(f"error: missing {EXE}", file=sys.stderr)
        return 1

    data = EXE.read_bytes()
    anchor_off = data.find(RIVER_TRANSITION)
    if anchor_off < 0:
        print("error: river transition anchor not found in VICEROY.EXE", file=sys.stderr)
        return 1

    ds_to_file_offset = anchor_off - DS_RIVER_TRANSITION

    extracted: dict[str, object] = {}
    for key, spec in TABLES.items():
        off = ds_to_file(spec["ds"], ds_to_file_offset)
        size = spec["count"] * spec["elem"]
        end = off + size
        if end > len(data):
            print(f"error: table {key} runs past end of EXE", file=sys.stderr)
            return 1
        blob = data[off:end]
        if spec["elem"] == 1:
            extracted[key] = list(blob)
        else:
            extracted[key] = [
                list(blob[i : i + spec["elem"]]) for i in range(0, size, spec["elem"])
            ]

    terrain_meta = extracted["terrain_meta"]
    assert terrain_meta[0][0] == 0 and terrain_meta[0][1] == 100 and terrain_meta[0][3] == 10
    assert terrain_meta[25][0] == 0
    assert terrain_meta[27][0] == 255
    assert terrain_meta[28][0] == 7

    parts = [
        "/* Generated by scripts/extract_viceroy_tables.py — do not edit. */",
        "",
        '#include "data/viceroy_tables.h"',
        "",
        f"const uint32_t viceroy_ds_to_file_offset = 0x{ds_to_file_offset:x}u;",
        "",
        format_matrix("viceroy_terrain_meta", terrain_meta),
        "",
        format_matrix("viceroy_tile_display", extracted["tile_display"]),
        "",
        format_array("viceroy_river_transition", extracted["river_transition"], 14),
        "",
        format_array("viceroy_feature_sprite_bases_a", extracted["feature_sprite_bases_a"], 4),
        "",
        format_array("viceroy_feature_sprite_bases_b", extracted["feature_sprite_bases_b"], 4),
        "",
        format_array("viceroy_connectivity_transition", extracted["connectivity_transition"], 14),
        "",
    ]

    OUT_C.parent.mkdir(parents=True, exist_ok=True)
    OUT_C.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT_C} (ds_to_file=0x{ds_to_file_offset:x}, anchor=0x{anchor_off:x})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
