#!/usr/bin/env python3
"""Extract static data tables from COLONIZE/VICEROY.EXE into src/data/viceroy_tables.c.

Usage: python3 scripts/extract_viceroy_tables.py
External requirements: Python 3 stdlib only; reads COLONIZE/VICEROY.EXE"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXE = ROOT / "COLONIZE" / "VICEROY.EXE"
OUT_C = ROOT / "src" / "data" / "viceroy_tables.c"

# Anchor: river transition table at DS:0x54de (verified against
# original_sources_decompiled/viceroy_unpacked.c usage).
DS_RIVER_TRANSITION = 0x54DE
RIVER_TRANSITION = bytes(
    [7, 4, 2, 1, 1, 0, 0, 7, 11, 13, 14, 0, 23, 44, 53, 73, 75, 0, 27, 22, 37, 18, 48, 0, 3, 20, 25, 5]
)

# Only terrain_meta is emitted: the tile_display / river / feature-base /
# connectivity tables this script used to generate had no consumer outside
# the smoke test that re-typed them as literals (duplication audit TT-27/28/29).
# The river table above stays as the EXE anchor, not as generated output.
TABLES = {
    "terrain_meta": {"ds": 0x543F, "count": 29, "elem": 0x34},
}


def ds_to_file(ds_offset: int, ds_to_file: int) -> int:
    return ds_offset + ds_to_file


def format_matrix(name: str, rows: list[list[int]]) -> str:
    elem = len(rows[0])
    lines = [f"const uint8_t {name}[{len(rows)}][{elem}] = {{"]
    for row in rows:
        lines.append("  {" + ", ".join(f"0x{b:02x}" for b in row) + "},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if not EXE.is_file():
        print(f"error: missing {EXE}", file=sys.stderr)
        return 1

    data = EXE.read_bytes()
    anchor_off = data.find(RIVER_TRANSITION)
    if anchor_off < 0:
        print("error: river transition anchor not found in VICEROY.EXE", file=sys.stderr)
        return 1

    ds_to_file_offset = anchor_off - DS_RIVER_TRANSITION

    extracted: dict[str, object] = {}
    for key, spec in TABLES.items():
        off = ds_to_file(spec["ds"], ds_to_file_offset)
        size = spec["count"] * spec["elem"]
        end = off + size
        if end > len(data):
            print(f"error: table {key} runs past end of EXE", file=sys.stderr)
            return 1
        blob = data[off:end]
        if spec["elem"] == 1:
            extracted[key] = list(blob)
        else:
            extracted[key] = [
                list(blob[i : i + spec["elem"]]) for i in range(0, size, spec["elem"])
            ]

    terrain_meta = extracted["terrain_meta"]
    assert terrain_meta[0][0] == 0 and terrain_meta[0][1] == 100 and terrain_meta[0][3] == 10
    assert terrain_meta[25][0] == 0
    assert terrain_meta[27][0] == 255
    assert terrain_meta[28][0] == 7

    parts = [
        "/* Generated by scripts/extract_viceroy_tables.py — do not edit. */",
        "",
        '#include "data/viceroy_tables.h"',
        "",
        format_matrix("viceroy_terrain_meta", terrain_meta),
        "",
    ]

    OUT_C.parent.mkdir(parents=True, exist_ok=True)
    OUT_C.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT_C} (ds_to_file=0x{ds_to_file_offset:x}, anchor=0x{anchor_off:x})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
